Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "generic/centos7"
  c.vm.hostname = "default-generic-centos7.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-module10-default-generic-centos7"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
