Vagrant.configure("2") do |config|
	config.vm.box = "bento/centos-7.2"
	config.vm.box_check_update = false
 
	config.vm.provider "virtualbox" do |vb|
		vb.gui = false
		vb.memory = "512"
	end

	config.vm.define "server1" do |sr1|
		sr1.vm.hostname = "server1"
		sr1.vm.network "private_network", ip: "192.168.33.111"
		sr1.vm.provision "shell", privileged: false, inline: <<-SHELL 
			sudo yum install epel-release -y
			sudo yum install sshpass -y
			echo -e "Host *\n    StrictHostKeyChecking no\n" > ~/.ssh/config
			sudo chmod 600 ~/.ssh/config
			echo -e "192.168.33.112 server2\n192.168.33.111 server1\n127.0.0.1 server1\n127.0.0.1 localhost" | sudo tee -a /etc/hosts > /dev/null
			sudo echo -e 'y\n'|ssh-keygen -q -N "" -f ~/.ssh/id_rsa
		SHELL
	end

	config.vm.define "server2" do |sr2|
		sr2.vm.hostname = "server2"
		sr2.vm.network "private_network", ip: "192.168.33.112"
		sr2.vm.provision "shell", privileged: false, inline: <<-SHELL 
			sudo yum install epel-release -y
			sudo yum install sshpass -y
			echo -e "Host *\n    StrictHostKeyChecking no\n" > ~/.ssh/config
			sudo chmod 600 ~/.ssh/config
			echo -e "192.168.33.112 server2\n192.168.33.111 server1\n127.0.0.1 server2\n127.0.0.1 localhost" | sudo tee -a /etc/hosts > /dev/null
			sudo echo -e 'y\n'|ssh-keygen -q -N "" -f ~/.ssh/id_rsa
			sshpass -p vagrant ssh-copy-id vagrant@server1
			sshpass -p vagrant ssh vagrant@server1 "sshpass -p vagrant ssh-copy-id vagrant@server2"
		SHELL
	end
end