filebeat.config.modules:
  enabled: true
  path: ${path.config}/modules.d/*.yml
  
filebeat.inputs:
- type: log
  enabled: true
  paths:
      - /var/log/*/*.log
      - /var/log/*.log
  fields_under_root: true
  scan_frequency: 5s

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "http://kibana:5601"

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]