version: '3'
services:
  collectd2:
    build:
      ./col2
  collectd1:
    build:
      ./col1
  influx:
    image: influxdb
    environment:
      INFLUXDB_DB: collectd
    ports:
      - 25826:25826
      - 8083:8083
      - 8086:8086
      - 8090:8090
    volumes:
      - ./idb/types.db:/usr/share/collectd/types.db
      - ./idb/influxdb.conf:/etc/influxdb/influxdb.conf
  grafana:
    build:
      ./gra
    ports:
      - 3000:3000