name 'm10'
maintainer 'Aliaksandr Padrabinkin'
maintainer_email 'y6vmeq@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures m10'
long_description 'Installs/Configures m10'
chef_version '>= 13.0'
depends 'docker'
version '1.1.20'