version: '3.3'
services:
  registry:
    restart: always
    image: registry
    ports:
      - 5000:5000
    volumes:
      - ./config/config.yml:/etc/docker/registry/config.yml:ro
      - rg:/var/lib/registry:rw
volumes:
  rg: {}