def change_version = ''
node {
	stage('1.Get_branch') {
		git branch: 'task10', url: 'https://github.com/y6vmeq/EPAM.git'
		sh "git config --global user.email 'y6vmeq@gmail.com'"
		sh "git config --global user.name 'y6vmeq'"
		sh "chmod -R 777 ${env.WORKSPACE}/m10"
	}

	stage('2.Write_new_tag'){
		dir('m10/'){
			println ver
			change_version = "default['m10']['tag'] = '" +ver +"'"
			println change_version
			sh """sed -i "s/.*tag.*/$change_version/g" attributes/default.rb"""
			def pr =  readFile "${env.WORKSPACE}/m10/metadata.rb"
			ver_inc = pr.getProperty('version')
			ver_inc = ver_inc.replaceAll(/'/, "")
			String min=ver_inc.substring(ver_inc.lastIndexOf('.')+1)
			int m=min.toInteger()+1
			String maj=ver_inc.substring(0,ver_inc.lastIndexOf("."))
			String new_ver="version '"+maj+ "." +m+"'"
			println new
			sh """sed -i "s/.*version.*/$new_ver/g" metadata.rb"""
		}
	}
	
	stage('3.Insert_env'){
		def file_env = sh returnStdout:true, script: "knife environment show $ENV -F json"
		env_Prop = readJSON text: file_env;
		env_Prop.default_attributes.m10.tag = image_tag
		writeJSON file: "m10${ENV}.json", json: env_Prop
		sh "sudo knife environment from file m10${ENV}.json"
	}
	
	stage('4.Push_cookbook_env'){
		dir('m10/'){
			sh "berks install && berks upload"
			withCredentials([usernamePassword(credentialsId: 'vagrant_login', passwordVariable: 'PASS', usernameVariable: 'NAME')]) {
				sh "knife ssh 'chef_environment:$ENV' 'sudo chef-client' -x ${NAME} -P ${PASS}"
			}
		}
	}
	stage('5.Push_Git') {
		sh "git add *"
		sh "git commit -m 'new version from Jenkins'"
		withCredentials([usernamePassword(credentialsId: 'git_login', passwordVariable: 'PASS', usernameVariable: 'NAME')]) {
			sh "git push https://${NAME}:${PASS}@github.com/y6vmeq/EPAM.git task10"
		}
	}
}