Vagrant.configure("2") do |config|
	config.vm.box = "bento/centos-7.6"
	config.vm.box_check_update = false
 
	config.vm.provider "virtualbox" do |vb|
		vb.gui = false
		vb.memory = "2048"
	end
	
	config.vm.define "chef" do |chef|
		chef.vm.hostname = "chef"
		chef.vm.network "forwarded_port", guest: 80, host: 80
		chef.vm.network "forwarded_port", guest: 443, host: 443
		chef.vm.network "private_network", ip: "192.168.33.110"
		chef.vm.provision "shell", inline: <<-SHELL
			echo "192.168.33.110 chef" >> /etc/hosts
			echo "192.168.33.111 work" >> /etc/hosts
			echo "192.168.33.121 node1" >> /etc/hosts
			yum update -y && yum upgrade -y && yum clean all
			yum install ntp java-1.8.0-openjdk-devel wget git java-1.8.0-openjdk-devel -y
			systemctl start ntpd
			systemctl enable ntpd
			ntpq -p
            rpm -Uvh /vagrant/chef-server-core-12.19.31-1.el7.x86_64.rpm
			chef-server-ctl reconfigure
			chef-server-ctl install chef-manage
			chef-server-ctl reconfigure
			chef-manage-ctl reconfigure --accept-license
			chef-server-ctl user-create y6vmeq ALIAKSANDR PADRABINKIN y6vmeq@gmail.com 968637 -f /vagrant/tmp/y6vmeq.pem
			chef-server-ctl org-create y6vmeq_org 'y6vmeq organization, Inc.' --association_user y6vmeq --filename /vagrant/tmp/y6vmeq_org-validator.pem
		SHELL
	end

	config.vm.define "node1" do |node1|
		node1.vm.hostname = "node1"
		node1.vm.network "private_network", ip: "192.168.33.121"
		node1.vm.network "forwarded_port", guest: 5000, host: 5000
		node1.vm.provision "shell", inline: <<-SHELL
			echo "192.168.33.110 chef" >> /etc/hosts
			echo "192.168.33.111 work" >> /etc/hosts
			echo "192.168.33.121 node1" >> /etc/hosts
			yum update -y && yum upgrade -y && yum clean all
			yum install ntp nmap -y
			systemctl start ntpd
			systemctl enable ntpd
			ntpq -p
		SHELL
	end

	config.vm.define "work" do |work|
		work.vm.hostname = "work"
		work.vm.network "private_network", ip: "192.168.33.111"
		work.vm.network "forwarded_port", guest: 8080, host: 8080
		work.vm.provision "shell", inline: <<-SHELL
			echo "192.168.33.110 chef" >> /etc/hosts
			echo "192.168.33.111 work" >> /etc/hosts
			echo "192.168.33.121 node1" >> /etc/hosts
			yum update -y && yum upgrade -y && yum clean all
			yum install ntp curl git java-1.8.0-openjdk-devel -y
			rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
			rpm -Uvh /vagrant/jenkins-2.170-1.1.noarch.rpm
			rpm -Uvh /vagrant/chef-workstation-0.2.48-1.el6.x86_64.rpm
			systemctl enable jenkins
			systemctl start jenkins
			systemctl start ntpd
			systemctl enable ntpd
			usermod -aG vagrant jenkins
			ntpq -p
			chmod 777 /home/vagrant/
			cd /home/vagrant
			chef generate repo chef-repo
			mkdir -p /home/vagrant/chef-repo/.chef
			cp /vagrant/tmp/y6vmeq.pem /home/vagrant/chef-repo/.chef/y6vmeq.pem
			cp /vagrant/tmp/y6vmeq_org-validator.pem /home/vagrant/chef-repo/.chef/y6vmeq_org-validator.pem
			cp /vagrant/tmp/knife.rb /home/vagrant/chef-repo/.chef/
			git config --global user.email "y6vmeq@gmail.com"
			git config --global user.name "y6vmeq"
			echo 'export PATH="/opt/chefdk/embedded/bin:$PATH"' >> /home/vagrant/.bash_profile && source /home/vagrant/.bash_profile
			cd /home/vagrant/chef-repo
			knife ssl fetch
			knife environment from file /vagrant/example_m10.json
			knife bootstrap node1 -x vagrant -P vagrant -N node1 --sudo
			cp -r /vagrant/chef-repo/cookbooks/m10/ /home/vagrant/chef-repo/cookbooks/
			cd /home/vagrant/chef-repo/cookbooks/m10/
			berks install && berks upload
			knife node environment set node1 example_m10
			knife node run_list set node1 'recipe[m10::create]'
			knife ssh 'chef_environment:example_m10' 'sudo chef-client' -x vagrant -P vagrant
			knife node run_list set node1 'recipe[m10]'
		SHELL
	end
end